### ISSUE TITLE
Problem deploying to Heroku

### ISSUE THREAD

**Issue by twler** [hexojs/hexo-deployer-heroku#2]
I've updated the config file.  Running `hexo deploy` builds the folder and pushes to my repo, but deploy fails with the error:

`-----> Failed to detect set buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed`

I've tried deploying to Heroku git and to GitHub git with Heroku hook; both fail with the above error.

Is there a workaround for this?

**Comment by eeosk** [comment]
I had previously been running a Node.js app in that Heroku app, so I needed to clear the buildpack:

    heroku buildpacks:remove heroku/nodejs -a my-app-name

After doing that, the next `hexo deploy` was successful.  Closing this issue as a result.

**Comment by twler** [comment]
I had previously been running a Node.js app in that Heroku instance, so I needed to clear the buildpack:

    heroku buildpacks:remove heroku/nodejs -a my-app-name

After doing that, the next `hexo deploy` was successful.  Closing this issue.

**Comment by ftiernan** [comment]
Ran into the same problem on 4/10/20 and the solution provided above by tyrw worked for me.

`heroku buildpacks:remove heroku/nodejs -a my-app-name`
